ProductionProjectCV/Controllers/ClientHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Services;

namespace OnlineResumePortal.Controllers
{
    [AllowAnonymous]
    public class ClientHomeController : Controller
    {
        ServicesBl serviceBl = new ServicesBl();
        // GET: ClientHome
        public ActionResult Index()
        {
            var info = serviceBl.HomePageInfo();
            return View(info);
        }
    }
}

ProductionProjectCV/Controllers/LoginController.cs
using Services;
using Services.AggregateModel;
using Services.Model;
using System;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using System.Web.Security;

namespace OnlineResumePortal.Controllers
{

    public class LoginController : Controller
    {
        ServicesBl serviceBl = new ServicesBl();
        public ActionResult Index()
        {
            return View();
        }
        [AllowAnonymous]
        [HttpPost]
        public ActionResult Index(ResumeModel model)
        {
            try
            {
                var password = EncryptDecrypt.Encrypt(model.Password);
                var result = serviceBl.CheckLogin(model.Username, password);
                //return View();
                if (result)
                {
                    FormsAuthentication.SetAuthCookie(model.Username, true);
                    var loggedUser = serviceBl.GetSavedDetails(model.Username);
                    Session.Add("LoggedUser", loggedUser);
                }
                else
                {
                    if (string.IsNullOrEmpty(model.Username) || string.IsNullOrEmpty(model.Password))
                    {
                        ViewBag.Message = "Username or Password cannot be emply!";
                    }
                    ViewBag.Message = "Invalid Username or Password";
                    return View("Index");
                }
                return RedirectToAction("Index", "Home");
            }

            catch (Exception ex)
            {
                if (string.IsNullOrEmpty(model.Username) || string.IsNullOrEmpty(model.Password))
                {
                    ViewBag.Message = "Username or Password cannot be emply!";
                }
                if (ex.Message.Contains("MongoConnectionException"))
                {
                    ViewBag.Message = "Connection Issues!";
                }

                return View("Index");
            }


        }
        public ActionResult ForgotPassword()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ForgotPassword(ForgotPasswordModel model)
        {
            try
            {
                var result = serviceBl.GetSavedDetails(model.Username);
                model.Password = result.Password;
                var mailresult = SendEmail.Send(model.Username, EncryptDecrypt.Decrypt(model.Password));
                if (mailresult)
                {
                    ViewBag.Message = "Reset password is sent to ur email.";
                    return View("Index");
                }
                else
                {
                    ViewBag.Message = "Technical Issue, Please try again later.";
                    return View("Index");
                }
            }
            catch (Exception)
            {
                ViewBag.Message = "No username/email in database found.";
                return View("Index");
            }
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        //[NonAction]
        //public string MD5Hash(string input)
        //{
        //    StringBuilder hash = new StringBuilder();
        //    MD5CryptoServiceProvider md5provider = new MD5CryptoServiceProvider();
        //    byte[] bytes = md5provider.ComputeHash(new UTF8Encoding().GetBytes(input));

        //    for (int i = 0; i < bytes.Length; i++)
        //    {
        //        hash.Append(bytes[i].ToString("x2"));
        //    }
        //    return hash.ToString();
        //}

        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();

            // clear authentication cookie
            HttpCookie cookie1 = new HttpCookie(FormsAuthentication.FormsCookieName, "");
            cookie1.Expires = DateTime.Now.AddYears(-1);
            Response.Cookies.Add(cookie1);
            return RedirectToAction("Index", "Login");
        }

    }
}

ProductionProjectCV/Controllers/RegisterController.cs
using Services;
using Services.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace OnlineResumePortal.Controllers
{
    [AllowAnonymous]
    public class RegisterController : Controller
    {
        ServicesBl service = null;

        public RegisterController()
        {
            service = new ServicesBl();
        }
        // GET: Register
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(ResumeModel model, string ConfirmPassword)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (model.Password != ConfirmPassword)
                    {
                        ViewBag.Message = "Confirm password doesnot match!";
                        return View();
                    }
                    //var password = MD5Hash(model.Password);
                    var password = EncryptDecrypt.Encrypt(model.Password);

                    //var dPassword = EncryptDecrypt.Decrypt(password);
                    var temppassword = model.Password;
                    model.Password = password;
                    model.Username = model.Email;
                    string msg;
                    var registerResult = service.Register(model, out msg);

                    if (!registerResult)
                    {
                        ViewBag.Message = msg;
                        return View();
                    }
                    var emailresult = SendEmail.Send(model.Username, temppassword);
                    if (emailresult)
                    {
                        ViewBag.Message = "Welcome to resume portal! An email is sent to your email address.";
                    }
                    else
                    {
                        ViewBag.Message = "Welcome to resume portal! Due to some technical dificulties, email could not be sent!";
                    }
                    FormsAuthentication.SetAuthCookie(model.Username, true);
                    Session.Add("LoggedUser", model);
                    return RedirectToAction("Index", "Home");

                }
                else {
                    ViewBag.Message = "Please Fill all required all fields!";
                    return View();

                }
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View();
            }


        }

        //[NonAction]
        //public string MD5Hash(string input)
        //{
        //    StringBuilder hash = new StringBuilder();
        //    MD5CryptoServiceProvider md5provider = new MD5CryptoServiceProvider();
        //    byte[] bytes = md5provider.ComputeHash(new UTF8Encoding().GetBytes(input));

        //    for (int i = 0; i < bytes.Length; i++)
        //    {
        //        hash.Append(bytes[i].ToString("x2"));
        //    }
        //    return hash.ToString();
        //}

        
    }
}

ProductionProjectCV/Views/Login/ForgotPassword.cshtml
@model Services.AggregateModel.ForgotPasswordModel
@{
    ViewBag.Title = "Login Page";
    Layout = "~/Views/Shared/LoginLayout.cshtml";
}

<div class="login-box">
    <div class="login-logo">
        <a href="@Url.Action("Index","ClientHome")"><b>Resume</b>PORTAL</a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">Enter your username/email. We will send you an email.</p>
        <form action="@Url.Action("ForgotPassword","Login")" method="post">
            <div class="form-group has-feedback">
                @Html.TextBoxFor(m => m.Username, new { @class = "form-control", @placeholder = "Email / Username" })
                @*<input type="email" class="form-control" placeholder="Email">*@
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>
            <div class="row">
                <!-- /.col -->
                <div class="col-xs-4">
                    @*<button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>*@
                    <button class="btn btn-primary btn-block btn-flat">Reset</button>
                </div>

                <!-- /.col -->
            </div>
            <div style="font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif">
                @if (ViewBag.Message != null)
            { <span>@ViewBag.Message</span>}
            </div>
        </form>
        @*<div class="social-auth-links text-center">
                <p>- OR -</p>
                <a href="#" class="btn btn-block btn-social btn-facebook btn-flat">
                    <i class="fa fa-facebook"></i> Sign in using
                    Facebook
                </a>
                <a href="#" class="btn btn-block btn-social btn-google btn-flat">
                    <i class="fa fa-google-plus"></i> Sign in using
                    Google+
                </a>
            </div>*@
        <!-- /.social-auth-links -->
        @*<a href="#">I forgot my password</a><br>*@
    </div>
    <!-- /.login-box-body -->
</div>
@*@section scripts{
    <script>
        $(document).ready(function () {
            alert('Ready');
        })
    </script>
}*@

ProductionProjectCV/Views/Login/Index.cshtml
@model Services.Model.ResumeModel
@{
    ViewBag.Title = "Login Page";
    Layout = "~/Views/Shared/LoginLayout.cshtml";
}

<div class="login-box">
    <div class="login-logo">
        <a href="@Url.Action("Index","ClientHome")"><b>Resume</b>PORTAL</a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>
        <form action="@Url.Action("Index","Login")" method="post">
            <div class="form-group has-feedback">
                @Html.TextBoxFor(m=>m.Username,new {@class="form-control", @placeholder="Email / Username" })
                @*<input type="email" class="form-control" placeholder="Email">*@
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                @*<input type="password" class="form-control" placeholder="Password">*@
                @Html.TextBoxFor(m => m.Password, new { @class = "form-control", @placeholder = "Password" })
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="row">
                <!-- /.col -->
                <div class="col-xs-4">
                    @*<button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>*@
                    <button class="btn btn-primary btn-block btn-flat">Sign In</button>
                </div>
                
                <!-- /.col -->
            </div>
            <div style="font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif"> @if (ViewBag.Message != null) { <span>@ViewBag.Message</span>}</div>
        </form>
        @*<div class="social-auth-links text-center">
            <p>- OR -</p>
            <a href="#" class="btn btn-block btn-social btn-facebook btn-flat">
                <i class="fa fa-facebook"></i> Sign in using
                Facebook
            </a>
            <a href="#" class="btn btn-block btn-social btn-google btn-flat">
                <i class="fa fa-google-plus"></i> Sign in using
                Google+
            </a>
        </div>*@
        <!-- /.social-auth-links -->
        @*<a href="#">I forgot my password</a><br>*@
        <a href="@Url.Action("Index","Register")" class="text-center">Register a new membership</a>
        <a href="@Url.Action("ForgotPassword","Login")" class="text-center pull-right">Forgot Password</a>
    </div>
    <!-- /.login-box-body -->
</div>