ProductionProjectCV/Controllers/ClientHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Services;

namespace OnlineResumePortal.Controllers
{
    [AllowAnonymous]
    public class ClientHomeController : Controller
    {
        ServicesBl serviceBl = new ServicesBl();
        // GET: ClientHome
        public ActionResult Index()
        {
            var info = serviceBl.HomePageInfo();
            return View(info);
        }
    }
}

ProductionProjectCV/Controllers/ManageProfileController.cs
using Services;
using Services.AggregateModel;
using Services.Model;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineResumePortal.Controllers
{
    [CustomAuthorize]
    public class ManageProfileController : Controller
    {
        ServicesBl serviceBl = new ServicesBl();
        // GET: ManageProfile
        [HttpGet]
        public ActionResult Index()
        {
            var loggedUser = (Services.Model.ResumeModel)HttpContext.Session?["LoggedUser"];
            var getInfo = serviceBl.GetSavedDetails(loggedUser.Username);
            return View(getInfo);
        }
        [HttpPost]
        public ActionResult Index(ResumeModel instance, HttpPostedFileBase ImageFile)
        {
            var loggedUser = (Services.Model.ResumeModel)HttpContext.Session?["LoggedUser"];
            var getInfo = serviceBl.GetSavedDetails(loggedUser.Username);

            if (!string.IsNullOrEmpty(instance.PublicName))
            {
                var model = serviceBl.GetPublicResume(instance.PublicName);
                if (model != null)
                {
                    if (model._ResumeId == new Guid("00000000-0000-0000-0000-000000000000"))
                    {
                        getInfo.PublicName = instance.PublicName;
                    }
                }
                else
                {
                    getInfo.PublicName = instance.PublicName;
                }
            }
            else
            {
                ModelState.AddModelError("PublicName", "Public already taken, try differen Name!");
                return View(getInfo);
            }


            getInfo.FullName = instance.FullName;

            string extension = "";
            if (ImageFile != null)
            {
                bool folderExists = Directory.Exists(Server.MapPath("~/Image/ResumeImages/"));
                if (!folderExists)
                {
                    Directory.CreateDirectory(Server.MapPath("~/Image/ResumeImages/"));
                }
                string path = Server.MapPath("~/Image/ResumeImages/");
                path = string.Format("{0}{1}.jpg", path, getInfo._id.ToString());
                ImageFile.SaveAs(path);

                extension = Path.GetExtension(path);
                getInfo.ProfileImageName = getInfo._id.ToString() + extension;
                //ImageFile.SaveAs()
            }



            var result = serviceBl.DoUpsertAsync(getInfo);
            if (result.Exception == null)
            {
                ViewBag.Message = "Progress Saved!";
            }
            else
            {
                ViewBag.Message = "Something went wrong!";
            }
            var attach_model = new ResumeModel();
            return View(attach_model);
        }

        public ActionResult ChangePassword()
        {
            ChangePasswordModel model = new ChangePasswordModel();
            return View(model);
        }
        [HttpPost]
        public ActionResult ChangePassword(ChangePasswordModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.NewPassword != model.ConfirmPassword)
                {
                    ViewBag.Message = "Confirm password doesnot match!";
                    return View();
                }
                else
                {
                    var loggedUser = (Services.Model.ResumeModel)HttpContext.Session?["LoggedUser"];
                    var getInfo = serviceBl.GetSavedDetails(loggedUser.Username);
                    if (model.Password != EncryptDecrypt.Decrypt(getInfo.Password))
                    {
                        ViewBag.Message = "Wrong password! Please try again.";
                        return View();
                    }
                    getInfo.Password = EncryptDecrypt.Encrypt(model.NewPassword);
                    var result = serviceBl.DoUpsertAsync(getInfo);
                    if (result.Exception == null)
                    {
                        ViewBag.Message = "Progress Saved!";
                        ChangePasswordModel cmodel = new ChangePasswordModel();
                        return View(cmodel);
                    }
                    else
                    {
                        ViewBag.Message = "Something Went Wrong!";
                        return View();
                    }
                }
            }
            ViewBag.Message = "Please Fill All Required fields!";
            return View();
        }
    }
}

ProductionProjectCV/Controllers/MyResumeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace OnlineResumePortal.Controllers
{
    [CustomAuthorize]
    public class MyResumeController : Controller
    {
        Services.Model.ResumeModel loggedUser = new Services.Model.ResumeModel();
        Services.ServicesBl serviceBl = null;
        public MyResumeController()
        {
            serviceBl = new Services.ServicesBl();
        }


        public ActionResult Preview(Guid resumeId)
        {
            var model = new Services.Model.ResumeDetails();
            loggedUser = (Services.Model.ResumeModel)HttpContext.Session?["LoggedUser"];
            var getInfo = serviceBl.GetSavedDetails(loggedUser.Username);
            //var guid = new Guid(resumeId);
            var resumePreview = getInfo.Resumes.Where(x => x._ResumeId == resumeId).FirstOrDefault();
            ViewBag.ResumePreview = resumePreview;
            return View(resumePreview);
        }
        public ActionResult PublicPreview(Guid resumeId)
        {

            var list = serviceBl.List();
            var result = new List<Services.Model.ResumeDetails>();
            foreach (var item in list) {
                if (item.Resumes != null) { 
                result.AddRange(item.Resumes);
                }
            }
            var model = result.Where(x => x._ResumeId == resumeId).FirstOrDefault();
            return View("Preview", model);
        }

        // GET: MyResume
        public ActionResult Detail()
        {
            return View();
        }

        public ActionResult Index()
        {
            loggedUser = (Services.Model.ResumeModel)HttpContext.Session?["LoggedUser"];
            var getInfo = serviceBl.GetSavedDetails(loggedUser.Username);
            if (getInfo.Resumes != null)
            {
                var resumelist = getInfo.Resumes;
                ViewBag.ResumeList = resumelist;
            }
            return View();
        }
        public ActionResult Form()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Services.Model.ResumeDetails model, HttpPostedFileBase ImageFile)
        {
            if (string.IsNullOrEmpty(model.ResumeTitle))
            {
                ModelState.AddModelError("Title", "Title is requiried!");
                return View("Form", model);
            }
            var LoggerUser = new Services.Model.ResumeModel();
            LoggerUser = (Services.Model.ResumeModel)Session["LoggedUser"];
            var resumeresult = serviceBl.GetSavedDetails(LoggerUser.Username).Resumes;
            if (model.SetActive != null)
            {
                if (model.SetActive == "on")
                {
                    if (resumeresult != null)
                    {
                        foreach (var r in resumeresult)
                        {
                            r.SetActive = "Off";
                        }
                    }
                }
            }
            else
            {
                model.SetActive = "off";
            }
            LoggerUser.Resumes = resumeresult;
            if (model != null)
                model._ResumeId = Guid.NewGuid();
            string extension = "";
            if (ImageFile != null)
            {
                bool folderExists = Directory.Exists(Server.MapPath("~/Image/ResumeImages/"));
                if (!folderExists)
                {
                    Directory.CreateDirectory(Server.MapPath("~/Image/ResumeImages/"));
                }
                string path = Server.MapPath("~/Image/ResumeImages/");
                path = string.Format("{0}{1}.jpg", path, model._ResumeId.ToString());
                ImageFile.SaveAs(path);

                extension = Path.GetExtension(path);
                //ImageFile.SaveAs()
            }
            var ImageName = new Services.Model.Image();
            ImageName.Name = model._ResumeId.ToString() + extension;
            model.Image = ImageName;
            if (model.EducationInfos != null)
            {
                model.EducationInfos.FirstOrDefault()._EducationId = Guid.NewGuid();
            }
            if (model.JobHistories != null)
            {
                model.JobHistories.FirstOrDefault()._HistoryId = Guid.NewGuid();
            }
            if (model.Skills != null)
            {
                model.Skills.FirstOrDefault()._SkillId = Guid.NewGuid();
            }
            if (model.Languages != null)
            {
                model.Languages.FirstOrDefault()._LanguageId = Guid.NewGuid();
            }
            if (LoggerUser.Resumes == null)
            {
                LoggerUser.Resumes = new List<Services.Model.ResumeDetails>();
            }
            LoggerUser.Resumes.Add(model);
            var result = serviceBl.DoUpsertAsync(LoggerUser);
            if (result.Exception == null)
            {
                ViewBag.Message = "Progress Saved!";
                loggedUser = (Services.Model.ResumeModel)HttpContext.Session?["LoggedUser"];
                var getInfo = serviceBl.GetSavedDetails(loggedUser.Username);
                if (getInfo.Resumes != null)
                {
                    var resumelist = getInfo.Resumes;
                    ViewBag.ResumeList = resumelist;
                }
                return View("Index");
            }
            else
            {
                ViewBag.Message = "Something went wrong !Progress not Saved!";
                loggedUser = (Services.Model.ResumeModel)HttpContext.Session?["LoggedUser"];
                var getInfo = serviceBl.GetSavedDetails(loggedUser.Username);
                if (getInfo.Resumes != null)
                {
                    var resumelist = getInfo.Resumes;
                    ViewBag.ResumeList = resumelist;
                }
                return View("Index");
            }
        }
        public ActionResult Delete(string Id)
        {
            var guid = new Guid(Id);
            var loggedUser = (Services.Model.ResumeModel)HttpContext.Session?["LoggedUser"];
            var getInfo = serviceBl.GetSavedDetails(loggedUser.Username);
            var resumes = getInfo.Resumes;
            var resumeTobeDeleted = resumes.Where(x => x._ResumeId == guid).FirstOrDefault();
            resumes.Remove(resumeTobeDeleted);
            getInfo.Resumes = resumes;
            var result = serviceBl.DoUpsertAsync(getInfo);
            if (result.Exception == null)
            {
                ViewBag.Message = "Progress Saved!";
                //return View("Index");
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Message = "Something went wrong !Progress not Saved!";
                //return View("Index");
                return RedirectToAction("Index");


            }
        }

    }
}

ProductionProjectCV/Controllers/ResumesController.cs
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace OnlineResumePortal.Controllers
{
    public class ResumesController : Controller
    {
        ServicesBl serviceBl = new ServicesBl();
        // GET: Resumes
        public ActionResult Public (string id)
        {
            var model = serviceBl.GetPublicResume(id);
            if (model != null)
            {
                if (model._ResumeId == new Guid("00000000-0000-0000-0000-000000000000"))
                    return RedirectToAction("Index", "NotFound");
            }
            else {
                return RedirectToAction("Index", "NotFound");
            }
            return View("Index",model);
        }

        [CustomAuthorize]
        [HttpGet]
        public ActionResult FindResumes(/*string queryString*/)
        {

            //var result = serviceBl.FindProfile(queryString);
            return View();
        }
        [CustomAuthorize]
        [HttpPost]
        public ActionResult FindResumes(string queryString)
        {

            var result = serviceBl.FindProfile(queryString);
            //return View();
            return PartialView("_PartialFindResumes", result);

        }

       }
}

ProductionProjectCV/Views/Shared/LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="~/Content/Main/bootstrap/css/bootstrap.min.css">
    <link href="~/Content/Main/select2.min.css" rel="stylesheet" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Content/Main/dist/css/AdminLTE.min.css">

    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <!-- iCheck -->
    <link href="~/Content/Main/plugins/iCheck/square/blue.css" rel="stylesheet" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body class="hold-transition login-page">
        <!-- Content Wrapper. Contains page content -->

            <!-- Content Header (Page header) -->
            <!-- Main content -->


                @RenderBody()



        <!-- /.control-sidebar -->
        <!-- Add the sidebar's background. This div must be placed
             immediately after the control sidebar -->

    <!-- ./wrapper -->
    <!-- jQuery 2.2.3 -->
    <script src="~/Scripts/plugins/jQuery/jquery-2.2.3.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/Scripts/bootstrap/js/bootstrap.min.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/Scripts/plugins/iCheck/icheck.min.js"></script>
    <script src="~/Scripts/select2.full.min.js"></script>

    <script>
        $(function () {
            $('.select2').selec2();
            $('input').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue',
                increaseArea: '20%' // optional
            });
        });
        $(document).ready(function () {
            $('.select2').selec2();
        });
    </script>
</body>
@RenderSection("Scripts", false)
</html>

ProductionProjectCV/Views/Shared/_ClientHome.cshtml
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Resume Portal</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Resume Portal" />
    <meta name="keywords" content="Resume, CV" />
    <meta name="author" content="atutgorkhali.com.np" />
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,700,800" rel="stylesheet">

    <!-- Animate.css -->
    <link href="~/Content/css/animate.css" rel="stylesheet" />
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="~/Content/css/icomoon.css">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="~/Content/css/bootstrap.css">

    <!-- Magnific Popup -->
    <link rel="stylesheet" href="~/Content/css/magnific-popup.css">

    <!-- Owl Carousel  -->
    <link rel="stylesheet" href="~/Content/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Content/css/owl.theme.default.min.css">

    <!-- Theme style  -->
    <link rel="stylesheet" href="~/Content/css/style.css">

    <!-- Modernizr JS -->
    <script src="~/Content/js/modernizr-2.6.2.min.js"></script>
    <!-- FOR IE9 below -->
    <!--[if lt IE 9]>
    <script src="js/respond.min.js"></script>
    <![endif]-->

</head>
<body>

    <div class="fh5co-loader"></div>

    @RenderBody()

    <div class="gototop js-top">
        <a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
    </div>

    <!-- jQuery -->
    <script src="~/Content/js/jquery.min.js"></script>
    <!-- jQuery Easing -->
    <script src="~/Content/js/jquery.easing.1.3.js"></script>
    <!-- Bootstrap -->
    <script src="~/Content/js/bootstrap.min.js"></script>
    <!-- Waypoints -->
    <script src="~/Content/js/jquery.waypoints.min.js"></script>
    <!-- Stellar Parallax -->
    <script src="~/Content/js/jquery.stellar.min.js"></script>
    <!-- Carousel -->
    <script src="~/Content/js/owl.carousel.min.js"></script>
    <!-- countTo -->
    <script src="~/Content/js/jquery.countTo.js"></script>
    <!-- Magnific Popup -->
    <script src="~/Content/js/jquery.magnific-popup.min.js"></script>
    <script src="~/Content/js/magnific-popup-options.js"></script>
    <!-- Main -->
    <script src="~/Content/js/main.js"></script>

</body>
</html>

ProductionProjectCV/Views/Shared/_Header.cshtml
@{
    Services.Model.ResumeModel data = new Services.Model.ResumeModel();
    data = (Services.Model.ResumeModel)Session["LoggedUser"];
}
<header class="main-header">
    <!-- Logo -->
    <a href="@Url.Action("Index","Home")" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>CV</b></span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>Resume</b>PORTAL</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- Messages: style can be found in dropdown.less-->
                <!-- Notifications: style can be found in dropdown.less -->


                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-gears"></i>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            @if (string.IsNullOrEmpty(data.ProfileImageName))
            {
                                <img src="~/Image/ResumePORTAL/user_nopic.png" class="img-circle" alt="User Image">
                            }
                            else
                            {
                                <img src="~/Image/ResumeImages/@data.ProfileImageName" class="img-circle" alt="User Image">
                            }

                            <p>
                                @if (string.IsNullOrEmpty(data.FullName))
                                {
                                <p>@data.Username</p>
                                }
                                else
                                {
                                    <p>@data.FullName</p>
                                }
                                @*<small>Member since Nov. 2012</small>*@
                                </p>
                            </li>

                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="@Url.Action("Index","ManageProfile")" class="btn btn-default btn-flat">Manage Profile</a>
                                </div>
                                <div class="pull-right">
                                    <a href="@Url.Action("LogOff","Login")" class="btn btn-default btn-flat">Sign out</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                    <!-- Control Sidebar Toggle Button -->
                    @*<li>
                            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                        </li>*@
                </ul>
            </div>
        </nav>
    </header>

ProductionProjectCV/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="~/Content/Main/bootstrap/css/bootstrap.min.css">
    <link href="~/Content/Main/select2.min.css" rel="stylesheet" />

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Content/Main/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link href="~/Content/Main/font-awesome-4.7.0/css/font-awesome.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/Main/dist/css/skins/_all-skins.min.css">
    <!-- iCheck -->
    @*<link rel="stylesheet" href="~/Content/Main/plugins/iCheck/flat/blue.css">*@
    <!-- Morris chart -->
    <!-- jvectormap -->
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="~/Content/Main/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">

    <link href="~/Content/plugins/iCheck/square/blue.css" rel="stylesheet" />


    @*<link href="~/Content/css/style.css" type="text/css" rel="stylesheet" rev="stylesheet" media="screen">
    <link href="~/Content/css/print.css" type="text/css" rel="stylesheet" rev="stylesheet" media="print">
    <link href="~/Content/fancybox/jquery.fancybox-1.3.0.css" type="text/css" rel="stylesheet" rev="stylesheet" media="screen">*@

    <link href="~/Content/Main/custom.css" rel="stylesheet" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        @Html.Partial("~/Views/Shared/_Header.cshtml")
        @Html.Partial("~/Views/Shared/_Sidebar.cshtml")
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <!-- Main content -->
            <section class="content">

                @RenderBody()
            </section>
            <!-- /.content -->
        </div>

        <!-- /.control-sidebar -->
        <!-- Add the sidebar's background. This div must be placed
             immediately after the control sidebar -->
        <div class="control-sidebar-bg"></div>
    </div>
        <script src="~/Scripts/plugins/jQuery/jquery-2.2.4.min.js"></script>
    <script src="~/Scripts/plugins/jQuery/jquery-1.10.2.min.js"></script>
    <!-- ./wrapper -->
    <!-- jQuery 2.2.3 -->
    @*<script src="~/Scripts/plugins/jQuery/jquery-2.2.3.min.js"></script>*@
    <!-- jQuery UI 1.11.4 -->
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.6 -->
    <script src="~/Scripts/bootstrap/js/bootstrap.min.js"></script>
    <!-- Morris.js charts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <!-- Sparkline -->
    <!-- jvectormap -->
    <!-- jQuery Knob Chart -->
    <!-- AdminLTE App -->
    <script src="~/Scripts/dist/js/app.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    @*<script src="~/Scripts/dist/js/pages/dashboard.js"></script>*@
    <!-- AdminLTE for demo purposes -->
    @*<script src="~/Scripts/plugins/iCheck/icheck.min.js"></script>*@


    @*<script>
        $(function () {
            $('input').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue',
                increaseArea: '20%' // optional
            });
        });
    </script>*@
    @RenderSection("scripts", required: false)
    
</body>
</html>

ProductionProjectCV/Views/Shared/_Sidebar.cshtml
@{
    Services.Model.ResumeModel data = new Services.Model.ResumeModel();
    data = (Services.Model.ResumeModel)Session["LoggedUser"];
}
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->

    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                @if (string.IsNullOrEmpty(data.ProfileImageName))
            {
                    <img src="~/Image/ResumePORTAL/user_nopic.png" class="img-circle" alt="User Image">
                }
                else
                {
                    <img src="~/Image/ResumeImages/@data.ProfileImageName" class="img-circle" alt="User Image">
                }
            </div>
            <div class="pull-left info">
               @if (string.IsNullOrEmpty(data.FullName))
               {
                   <p>@data.Username</p>
               }
               else {
                   <p>@data.FullName</p>
               }
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu">
            <li>
                <a href="@Url.Action("Index","MyResume")">
                    <i class="fa fa-th"></i> <span>My Resume</span>
                    @*<span class="pull-right-container">
                            <small class="label pull-right bg-green">new</small>
                        </span>*@
                </a>
            </li>
            <li>
                <a href="@Url.Action("FindResumes","Resumes")">
                    <i class="fa fa-search"></i> <span>Find Resumes</span>
                    @*<span class="pull-right-container">
                    <small class="label pull-right bg-green">new</small>
                </span>*@
                </a>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-pie-chart"></i>
                    <span>Settings</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="pages/charts/chartjs.html"><i class="fa fa-circle-o"></i> Set Visibility</a></li>
                    <li><a href="pages/charts/morris.html"><i class="fa fa-circle-o"></i> Profile</a></li>
                    <li><a href="@Url.Action("ChangePassword","ManageProfile")"><i class="fa fa-gear"></i> Change Password</a></li>
                    @*<li><a href="pages/charts/flot.html"><i class="fa fa-circle-o"></i> Flot</a></li>
                        <li><a href="pages/charts/inline.html"><i class="fa fa-circle-o"></i> Inline charts</a></li>*@
                </ul>
            </li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>